name: sultanbrowser

description: Top Featured Browser made by AB Production

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  gradient_app_bar: ^0.1.3
  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^0.3.22+1
  share: ^0.6.4+3
#  speech_to_text: ^2.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true


  assets:
    - assets/